### ISSUE TITLE
Ctr+t shortcut

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue-manual#2]
i printed out, on paper, the shortcut list for the Score and noticed a shortcut that was not on my radar, tried it nothing happened...

https://kunstmusik.github.io/blue-manual/users/gettingStarted/primaryEditors/scoreTimeline/
In the shortcut list: Ctrl+t, show quick time dialog   
should be: 
Ctrl+t, show quick time dialog of selected ScoreObject

**Comment by kunstmusik** [comment]
Closed with fix in #9
