### ISSUE TITLE
typo in text on Tuning Processor

### ISSUE THREAD

**Issue by tjingboem** [kunstmusik/blue-manual#4]
Tuning Processor
Introduction
Parameters: pfield, baseFrequency, scalaFile

Converts Blue PCH notation to frequency according to scale values in a Scala scale file. The scale will default to 12TET **wheen** TuningProcessor is initially created.

**Comment by kunstmusik** [comment]
Fix in https://github.com/kunstmusik/blue-manual/pull/8
